### ISSUE TITLE
Wrong linkage to tidymodels/tidymodels

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/modeldata#17]
Description refer bug reports to tidymodels/tidymodels

https://github.com/tidymodels/modeldata/blob/7774fd19fa7c6bb98bb0ad38759559f2222cb7d3/DESCRIPTION#L15

And some of the links (including the Github icon top right) also links to tidymodels/tidymodels

<img width="417" alt="Screen Shot 2021-06-01 at 6 45 35 PM" src="https://user-images.githubusercontent.com/14034784/120411395-95c88300-c309-11eb-929d-833e071cf8d3.png">

**Comment by jromanowska** [comment]
I've also noticed that the description of "grants" dataset (https://modeldata.tidymodels.org/reference/grants.html) states "Ames Housing Data".

**Comment by hfrick** [comment]
thanks for the reports @EmilHvitfeldt and @jromanowska !
