### ISSUE TITLE
Multi class data set

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/modeldata#36]
I'm been working with {themis} documentation, and I had a hard time finding a good example data set that

1. Includes multiple classes (4 or more)
2. Didn't have any missing data in the response
3. Be a reasonable response for the data set

for now, I'm using the `credit_data` data set with the `Home` variables but I need to do some prep work

```r
credit_data0 <- credit_data %>%
  filter(Home != "ignore") %>%
  mutate(Home = as.character(Home))
```

For illustration, it works fine, but I worry about giving the wrong signal by balancing over an obvious non-response

**Comment by topepo** [comment]
I suggest using this one: 

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
data(hpc_data)

hpc_data %>% count(class)
#> # A tibble: 4 × 2
#>   class     n
#>   <fct> <int>
#> 1 VF     2211
#> 2 F      1347
#> 3 M       514
#> 4 L       259
```

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Perfect! I felt like I overlooked an example
