### ISSUE TITLE
Use LazyData!

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/modeldata#4]
Making LazyData https://github.com/tidymodels/modeldata/blob/master/DESCRIPTION#L11 `FALSE` means that users have to write an extra line of code that they are probably out of the habit of writing.

**Comment by topepo** [comment]
This was on purpose so that they won’t occupy any memory until you use them.

**Comment by alexpghayes** [comment]
😢

**Comment by rpruim** [comment]
Is this true?  See http://r-pkgs.had.co.nz/data.html, where @hadley recommends using lazy data and shows that the data do not take up memory until used:

### Quoted from above referene

If the DESCRIPTION contains LazyData: true, then datasets will be lazily loaded. This means that they won’t occupy any memory until you use them. The following example shows memory usage before and after loading the nycflights13 package. You can see that memory usage doesn’t change until you inspect the flights dataset stored inside the package.

```r
pryr::mem_used()
## 31.6 MB
library(nycflights13)
pryr::mem_used()
## 33.3 MB
invisible(flights)
pryr::mem_used()
## 74 MB
```

I recommend that you always include LazyData: true in your DESCRIPTION. devtools::create() does this for you.

**Comment by hadley** [comment]
Yeah, we should always be using `LazyData: true`

**Comment by rpruim** [comment]
I would love to use some of these as I refresh some examples in my packages.  I had hoped to do that and get the updates onto CRAN this week.  But if this can get to CRAN with `LazyData: true` first, that would be great.

Do you have other updates in the works, or could this be a simple edit of DESCRIPTION and submission to CRAN?
